#!/usr/bin/env node
const { execSync } = require('child_process');

try {
  execSync('pnpm format', { stdio: 'inherit' });
  execSync('pnpm lint', { stdio: 'inherit' });
} catch (err) {
  console.error('Lint or format failed, aborting commit.');
  process.exit(1);
}
